<a href="https://colab.research.google.com/github/rjsaito/Data-Science-Essentials/blob/master/Data_Structures_and_Algorithms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Structures

## Lists

Lists are the simplest form of data structures. They are what they seem - a list of values. Each one of them is numbered, starting from zero - the first one is numbered zero, the second 1, the third 2, etc. You can remove values from the list, and add new values to the end. Example: Your many cats' names.

In [0]:
ls = [1,2,3,4,5]

ls

[1, 2, 3, 4, 5]

You can change a value by index

In [0]:
ls[2] = 10

ls

[1, 2, 10, 4, 5]

You can add new values

In [0]:
ls.append(6)

ls

[1, 2, 10, 4, 5, 6]

You can:

- Remove the first matcing value
- Delete item at a specific index
- Pop item at specific index and return

In [0]:
ls.remove(10)

ls

[1, 2, 4, 5, 6]

In [0]:
del ls[1]

ls

[1, 4, 5, 6]

In [0]:
ls.pop(1)

4

In [0]:
len(ls)

3

### Linked List

A linked list is a sequence of data elements, which are connected together via links. Each data element contains a connection to another data element in form of a pointer. Python does not have linked lists in its standard library. We implement the concept of linked lists using the concept of nodes as discussed in the previous chapter. We have already seen how we create a node class and how to traverse the elements of a node. In this chapter we are going to study the types of linked lists known as singly linked lists. In this type of data structure there is only one link between any two data elements. We create such a list and create additional methods to insert, update and remove elements from the list.

A linked list is created by using the node class we studied in the last chapter. We create a Node object and create another class to use this node object. We pass the appropriate values thorugh the node object to point the to the next data elements. The below program creates the linked list with three data elements. In the next section we will see how to traverse the linked list.

In [0]:
# Create Class Node
# need: dataval and nextval
class Node:
  def __init__(self, dataval):
    self.dataval = dataval
    self.nextval = None
  
  
# Create Class LinkedList
# need: headval
# also create print function
class LinkedList:
  def __init__(self):
    self.headval=None
    
  # create printlist function with recursion
  def printlist(self):
    printval = self.headval
    while printval is not None:
      print(printval.dataval)
      printval = printval.nextval

In [0]:
# initialize list
lst = LinkedList()

# assign node
lst.headval = Node("Mon")

# create other nodes
e2 = Node("Tues")
e3 = Node("Wed")

# assign and create pointers
lst.headval.nextval = e2
lst.headval.nextval.nextval = e3

# print linked list
lst.printlist()

Mon
Tues
Wed


## Tuples

Tuples are just like lists, but you can't change their values. The values that you give it first up, are the values that you are stuck with for the rest of the program. Again, each value is numbered starting from zero, for easy reference. Example: the names of the months of the year.

In [0]:
months = ('January','February','March','April','May','June',\
'July','August','September','October','November','  December')

In [0]:
months[2]

'March'

In [0]:
# not run
# del months[2]

In [0]:
len(months)

12

## Dictionaries

Dictionaries are similar to what their name suggests - a dictionary. In a dictionary, you have an 'index' of words, and for each of them a definition. In python, the word is called a 'key', and the definition a 'value'. The values in a dictionary aren't numbered - tare similar to what their name suggests - a dictionary. In a dictionary, you have an 'index' of words, and for each of them a definition. In python, the word is called a 'key', and the definition a 'value'. The values in a dictionary aren't numbered - they aren't in any specific order, either - the key does the same thing. You can add, remove, and modify the values in dictionaries.

When you initially create a dictionary, it is very much like making a tuple or list. Tuples have ( and ) things, lists have [ and ] things. Guess what! dictionaries have { and } things - curly braces. Here is an example below, showing a dictionary with four phone numbers in it.

In [0]:
#Make a phone book:

phonebook = {
'Andrew Parson':8806336, 
'Emily Everett':6784346, 
'Peter Power':7658344, 
'Lewis Lame':1122345
}

phonebook

{'Andrew Parson': 8806336,
 'Emily Everett': 6784346,
 'Lewis Lame': 1122345,
 'Peter Power': 7658344}

Add the person 'Gingerbread Man' to the phonebook:

In [0]:
phonebook['Gingerbread Man'] = 1234567

phonebook

{'Andrew Parson': 8806336,
 'Emily Everett': 6784346,
 'Gingerbread Man': 1234567,
 'Lewis Lame': 1122345,
 'Peter Power': 7658344}

Delete entry

In [0]:
del phonebook['Andrew Parson']

phonebook

{'Emily Everett': 6784346,
 'Gingerbread Man': 1234567,
 'Lewis Lame': 1122345,
 'Peter Power': 7658344}

In [0]:
len(phonebook)

4

Use f-string

In [0]:
if 'Peter Power' in phonebook:
    print(f'Peter Power has number {phonebook["Peter Power"]}')

Peter Power has number 7658344


## Arrays (Numpy) 

Consider Arrays over Lists / Dictionaries if

- Your data is 2-dimensional (or higher). Although nested dictionaries/lists can be used to represent multi-dimensional data, in most situations numpy arrays will be more efficient.
- You have to perform a bunch of numerical calculations. As already pointed out by zhqiat, numpy will give a significant speed-up in this case. Furthermore numpy arrays come bundled with a large amount of mathematical functions.

More on arrays: https://chrisalbon.com/

### Create
- Vector
- Matrix
- Tensor
- Sparse Matrix


In [0]:
import numpy as np

vector = np.array([1, 2, 3, 4, 5, 6])

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 2]])

tensor = np.array([
                    [[[1, 1], [1, 1]], [[2, 2], [2, 2]]],
                    [[[3, 3], [3, 3]], [[4, 4], [4, 4]]]
                  ])

print("Vector")
print(vector)
print(vector.shape)
print("\nMatrix")
print(matrix)
print(matrix.shape)
print("\nTensor")
print(tensor)
print(tensor.shape)

Vector
[1 2 3 4 5 6]
(6,)

Matrix
[[1 2 3]
 [4 5 6]
 [7 8 2]]
(3, 3)

Tensor
[[[[1 1]
   [1 1]]

  [[2 2]
   [2 2]]]


 [[[3 3]
   [3 3]]

  [[4 4]
   [4 4]]]]
(2, 2, 2, 2)


In [0]:
# create sparse matrix
from scipy import sparse

matrix = np.array([
    [0,0], 
    [0,1], 
    [3,0]]
)

# create compressed matrix
matrix_sparse = sparse.csr_matrix(matrix)
print(*matrix_sparse,)

   (0, 1)	1   (0, 0)	3


### Tranpose

In [0]:
print(vector.T)
print(matrix.T)

[1 2 3 4 5 6]
[[0 0 3]
 [0 1 0]]


### Reshape

In [0]:
vector.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
matrix.flatten()

array([0, 0, 0, 1, 3, 0])

### Invert

In [0]:
#np.linalg.inv(matrix)

## Series (Pandas)

Series is a one-dimensional labeled array capable of holding any data type (integers, strings, floating point numbers, Python objects, etc.). The axis labels are collectively referred to as the index.

The pandas series object can be seen as an enhanced numpy 1D array and the pandas dataframe can be seen as an enhanced numpy 2D array. The main difference is that pandas series and pandas dataframes has explicit index, while numpy arrays has implicit indexation

You can pass:
- a Python dict
- an ndarray
- a scalar value (like 5)

In [0]:
import numpy as np
import pandas as pd

In [0]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])

s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [0]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [0]:
s[0] + s[1]

4.0

In [0]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])

s

a   -0.795524
b   -1.557781
c    0.711613
d   -0.770555
e   -1.249258
dtype: float64

In [0]:
s.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [0]:
s['a']

-0.7955237589649377

In [0]:
s[0]

-0.7955237589649377

## Dataframes (Pandas)

In [0]:
city_names = pd.Series(['San Francisco', 'San Jose', 'Austin'])
state = pd.Categorical(['California', 'California', 'Texas'])
population = np.array([852469, 1015785, 485199])

city = pd.DataFrame({ 'City name': city_names, 'State': state,  'Population': population })

print(city)
print("\n")
print(city.dtypes)



       City name  Population       State
0  San Francisco      852469  California
1       San Jose     1015785  California
2         Austin      485199       Texas


City name       object
Population       int64
State         category
dtype: object


In [0]:
city.to_json()

'{"City name":{"0":"San Francisco","1":"San Jose","2":"Austin"},"Population":{"0":852469,"1":1015785,"2":485199},"State":{"0":"California","1":"California","2":"Texas"}}'

### Pandas Operations

In [0]:
# Select
city[['State', 'Population']]

State  Population
0  California      852469
1  California     1015785
2       Texas      485199

In [0]:
# Filter
city.query('State == "California"')

City name  Population       State
0  San Francisco      852469  California
1       San Jose     1015785  California

In [0]:
# Arrange
city.sort_values('Population')

City name  Population       State
2         Austin      485199       Texas
0  San Francisco      852469  California
1       San Jose     1015785  California

In [0]:
# Group by Sum
city.groupby('State').agg({'Population' : {'mean_pop' : 'mean', 'sum_pop' : 'sum'}}) # pass dict to specifiy column name

/usr/local/lib/python3.6/dist-packages/pandas/core/groupby.py:4291: FutureWarning: using a dict with renaming is deprecated and will be removed in a future version
  return super(DataFrameGroupBy, self).aggregate(arg, *args, **kwargs)


Population         
             mean_pop  sum_pop
State                         
California     934127  1868254
Texas          485199   485199

# Operations

## In-line Loop

In [0]:
# create tuple
tup = ('Abby', 'Chris', 'Deb')
tup

('Abby', 'Chris', 'Deb')

In [0]:
any(t == 'Abby' for t in tup)

True

## Lambda Function

Why Use Lambda Functions?
The power of lambda is better shown when you use them as an anonymous function inside another function.

Say you have a function definition that takes one argument, and that argument will be multiplied with an unknown number:

In [0]:
def myfunc(n):
  return lambda a : a * n

Use that function definition to make a function that always doubles the number you send in:

In [0]:
# create a lambda function by passing on value of n
mydoubler = myfunc(2)

print(mydoubler(11))

22


## Map Function

map functions expects a function object and any number of iterables like list, dictionary, etc. It executes the function_object for each element in the sequence and returns a list of the elements modified by the function object.

In [0]:
def multiply2(x):
  return x * 2
  
# unpacking generalization with asterisk  
out = *map(multiply2, [1, 2, 3, 4]),  # Output [2, 4, 6, 8]
out

(2, 4, 6, 8)

## Zip Function

The zip() function take iterables (can be zero or more), makes iterator that aggregates elements based on the iterables passed, and returns an iterator of tuples.

In [0]:
numberList = [1, 2, 3]
strList = ['one', 'two', 'three']

# Two iterables are passed
result = zip(numberList, strList)

# Converting itertor to set
resultSet = set(result)
print(resultSet)

{(2, 'two'), (1, 'one'), (3, 'three')}


## Vectorize

In [0]:
import numpy as np

matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

# create a lambda function
add_100 = lambda i: i + 100
  
# create vectorized function
vectorized_add_100 = np.vectorize(add_100)

#apply function
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

# Algorithms

## Recursion

Fibonnacci function

In [0]:
# create simple ficonnacci (with recursion)
def fib(n):
  if n == 0:
    return 0
  elif n == 1:
    return 1
  else:
    return fib(n-1) + fib(n-2)

In [0]:
fib(5)

5

### Memoization

In [0]:
# create a fibonnaci function, with memoization
# create a mamoization function to remember calculated values

def memoize(f):
  memo = {}
  def helper(x):
    if x not in memo:
      memo[x] = f(x)
    return memo[x]
  return helper
  

In [0]:
fib = memoize(fib)

fib(50)

12586269025

## Searching and Sorting

## Trees and Tree Algorithms

## Graphs and Graph Algorithm